### ISSUE TITLE
deal gracefully with IOError when learntris exits prematurely

### ISSUE THREAD

**Issue by tangentstorm** [tangentcode/learntris#39]
Example: implementation quits when `g` is received and testris is still trying to send the matrix data. You'll get:

```
Running test 3: io.g
g : given
---- sending commands ----
g
. . . . . . . . . .
. . . . . . . . . .
. . . . . . . . . .
. . . . . . . . . .
m m m m m m m m m m
b b b b b b b b b b
c c c c c c c c c c
g g g g g g g g g g
y y y y y y y y y y
o o o o o o o o o o
r r r r r r r r r r
. . . . . . . . . .
. . . . . . . . . .
Traceback (most recent call last):
  File "testris.py", line 158, in <module>
    main()
  File "testris.py", line 155, in main
    if program_args: run_tests(program_args[0], program_args[1])
  File "testris.py", line 131, in run_tests
    run_test(program, opcodes)
  File "testris.py", line 101, in run_test
    program.stdin.write((cmd + "\n").encode('utf-8'))
IOError: [Errno 22] Invalid argument
```

**Comment by tangentstorm** [comment]
I am unable to duplicate the error using the following implementation on FreeBSD:

    #!/usr/bin/env python
    import sys
    if sys.stdin.readline().strip() == 'p':
        for i in range(22): print('. ' * 10)

Possibly this is a platform-specific issue?

**Comment by tangentstorm** [comment]
Probably was a real issue, but too much has changed. I'm just going to close this one for now.
