### ISSUE TITLE
Test 4 unknown issue

### ISSUE THREAD

**Issue by rohanhere** [tangentcode/learntris#43]
```
Traceback (most recent call last):
  File "testris.py", line 163, in main
    try: run_tests(cmdline, use_shell)
  File "testris.py", line 135, in run_tests
    run_test(program, opcodes)
  File "testris.py", line 111, in run_test
    program.stdin.flush()
OSError: [Errno 22] Invalid argument

Oh no! Testris encountered an unexpected problem while
attempting to run your program. Please report the above
traceback in the issue tracker, so that we can help you
with the problem and provide a better error message in
the future.
```

**Comment by raylu** [comment]
How did you run testris.py? (Also, could you hop on our [IRC](https://webchat.freenode.net/?channels=lpmc)?)

**Comment by raylu** [comment]
errno 22:
```
       EINVAL fd  is  attached  to  an  object  which  is unsuitable for writing; or the file was opened with the
              O_DIRECT flag, and either the address specified in buf, the value specified in count, or  the  cur‐
              rent file offset is not suitably aligned.
```

so I have no idea how that happened...

**Comment by tangentstorm** [comment]
This probably was a valid bug, but the subprocess stuff has all changed dramatically since 2015 (the old runner was written for python 2.7), so I'm just going to close this, and not be surprised if something similar crops up on the tanco issues list.
